# Generated by Django 5.1.1 on 2024-09-09 23:12

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('authentication', '0007_card_user'),
    ]

    operations = [
        migrations.CreateModel(
            name='EpicLink',
            fields=[
                ('epic_link_id', models.AutoField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=255)),
                ('description', models.TextField()),
            ],
        ),
        migrations.AddField(
            model_name='user',
            name='priority',
            field=models.IntegerField(choices=[(0, 'Normal'), (1, 'Moderado'), (2, 'Alto'), (3, 'Muito Alto')], default=0),
        ),
        migrations.AddField(
            model_name='user',
            name='epic_link',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='authentication.epiclink'),
        ),
    ]
