# Generated by Django 5.1.1 on 2024-09-09 23:13

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('authentication', '0008_epiclink_user_priority_user_epic_link'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='user',
            name='epic_link',
        ),
        migrations.RemoveField(
            model_name='user',
            name='priority',
        ),
        migrations.AddField(
            model_name='card',
            name='epic_link',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='authentication.epiclink'),
        ),
        migrations.AddField(
            model_name='card',
            name='priority',
            field=models.IntegerField(choices=[(0, 'Normal'), (1, 'Moderado'), (2, 'Alto'), (3, 'Muito Alto')], default=0),
        ),
    ]
