# Generated by Django 5.1 on 2024-09-10 10:50

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('authentication', '0009_remove_user_epic_link_remove_user_priority_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='list',
            name='order',
        ),
    ]
