# Generated by Django 5.1 on 2024-09-10 17:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('authentication', '0010_remove_list_order'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='card',
            name='epic_link',
        ),
        migrations.AddField(
            model_name='card',
            name='epic_link',
            field=models.ManyToManyField(to='authentication.epiclink'),
        ),
    ]
