# Generated by Django 5.1 on 2024-09-10 17:27

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('authentication', '0011_remove_card_epic_link_card_epic_link'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='card',
            name='epic_link',
        ),
        migrations.AddField(
            model_name='card',
            name='epic_link',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='authentication.epiclink'),
            preserve_default=False,
        ),
    ]
