# Generated by Django 5.1 on 2024-09-10 17:37

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('authentication', '0012_remove_card_epic_link_card_epic_link'),
    ]

    operations = [
        migrations.AddField(
            model_name='card',
            name='assigned',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='assigned_cards', to=settings.AUTH_USER_MODEL),
            preserve_default=False,
        ),
        migrations.DeleteModel(
            name='MemberCard',
        ),
    ]
